# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'managerwind.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        self.Form = Form
        Form.setObjectName("Form")
        Form.resize(760, 340)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(442, 10, 311, 321))
        self.frame.setStyleSheet("color: rgb(0, 255, 255);\n"
"\n"
"border-top: 2px solid rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);")
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setStyleSheet("border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setStyleSheet("border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setStyleSheet("border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Serif\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setStyleSheet("border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setStyleSheet("border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setStyleSheet("border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 2, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setStyleSheet("border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Serif\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setStyleSheet("border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout.addWidget(self.lineEdit_8)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Serif\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 421, 321))
        self.tableView.setStyleSheet("color: rgb(0, 255, 255);\n"
"\n"
"border-top: 2px solid rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);")
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.MainWindow = None
        self.ui = None

        self.button_functions_M()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Add Person"))
        self.label_8.setText(_translate("Form", "Фамилия"))
        self.label_10.setText(_translate("Form", "Имя"))
        self.label_9.setText(_translate("Form", "Файл фото (назв.)"))
        self.pushButton_2.setText(_translate("Form", "Change Person"))
        self.label_5.setText(_translate("Form", "Фамилия"))
        self.label_6.setText(_translate("Form", "Имя"))
        self.label_7.setText(_translate("Form", "Файл фото (назв.)"))
        self.label_4.setText(_translate("Form", "Id"))
        self.pushButton_3.setText(_translate("Form", "Delete Person"))
        self.label_3.setText(_translate("Form", "Id"))
        self.pushButton_4.setText(_translate("Form", "Назад"))

    def button_functions_M (self):
        self.pushButton.clicked.connect(lambda: self.ad())
        self.pushButton_2.clicked.connect(lambda: self.ch())
        self.pushButton_3.clicked.connect(lambda: self.dl())
        self.pushButton_4.clicked.connect(lambda: self.back())

    def back(self):
        from main import Ui_MainWindow
        self.Form.close()
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
