# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userwind.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        self.userwind = UserWindow
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(330, 390)
        UserWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pushButton = QtWidgets.QPushButton(UserWindow)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 311, 23))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("color: rgb(0, 255, 255);\n"
"\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Serif\";\n"
"\n"
"border-top-color: rgb(0, 255, 255);\n"
"border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(UserWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 322, 311, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("color: rgb(0, 255, 255);\n"
"\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Serif\";\n"
"\n"
"border-top-color: rgb(0, 255, 255);\n"
"border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(UserWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 290, 101, 23))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("color: rgb(0, 255, 255);\n"
"\n"
"background-color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Serif\";\n"
"\n"
"border-top-color: rgb(0, 255, 255);\n"
"border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(UserWindow)
        self.label.setGeometry(QtCore.QRect(10, 291, 201, 20))
        self.label.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(UserWindow)
        self.label_3.setGeometry(QtCore.QRect(170, 40, 151, 231))
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_3.setStyleSheet("border-top: 2px solid rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";\n"
"color: rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(UserWindow)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 151, 231))
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_4.setStyleSheet("border-top: 2px solid rgb(0, 255, 255);\n"
"font:  10pt \"MS Serif\";\n"
"color: rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(UserWindow)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 360, 101, 23))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("color: rgb(0, 255, 255);\n"
"\n"
"background-color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Serif\";\n"
"\n"
"border-top-color: rgb(0, 255, 255);\n"
"border-top: 2px solid rgb(0, 255, 255);\n"
"border-left: 2px solid rgb(0, 255, 255);\n"
"border-right: 2px solid rgb(0, 255, 255);\n"
"border-bottom: 2px solid rgb(0, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(UserWindow)
        self.label_2.setGeometry(QtCore.QRect(120, 360, 201, 20))
        self.label_2.setStyleSheet("color: rgb(0, 255, 255);\n"
"font: 10pt \"MS Serif\";")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(UserWindow)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

        self.MainWindow = None
        self.ui = None

        self.button_functions_U()

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "Form"))
        self.pushButton.setText(_translate("UserWindow", "СОЕДИНЕНИЕ С СЕРВЕРОМ"))
        self.pushButton_2.setText(_translate("UserWindow", "ОТПРАВИТЬ ЗАПРОС"))
        self.pushButton_3.setText(_translate("UserWindow", "Выбарть файл"))
        self.label.setText(_translate("UserWindow", "-------------  Файл не выбран  -------------"))
        self.label_3.setText(_translate("UserWindow", "Фото не загружено"))
        self.label_4.setText(_translate("UserWindow", "Фото на загружено"))
        self.pushButton_4.setText(_translate("UserWindow", "Назад"))
        self.label_2.setText(_translate("UserWindow", " Нобатов И. - ИУ5-14М"))

    def button_functions_U (self):
        self.pushButton.clicked.connect(lambda: self.connection())
        self.pushButton_2.clicked.connect(lambda: self.accessrequest())
        self.pushButton_3.clicked.connect(lambda: self.addfile())
        self.pushButton_4.clicked.connect(lambda: self.back())

    def connection(self):
        print('connect')

    def addfile(self):
        print('addfile')

    def back(self):
        from main import Ui_MainWindow
        self.userwind.close()
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()

    def accessrequest(self):
        print('access')
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     UserWindow = QtWidgets.QWidget()
#     ui = Ui_UserWindow()
#     ui.setupUi(UserWindow)
#     UserWindow.show()
#     sys.exit(app.exec_())
